select m.days,m.jid,info_id '批次',sum(m.total)'邀请', sum(m.read_count)'已读', sum(m.operate_count)'接受',
format(100*sum(m.read_count)/sum(m.total),2) '阅读率%',
format(100*sum(m.operate_count)/ sum(m.read_count),2) '接受率%',
format(100*sum(m.operate_count)/sum(m.total),2) '总接受率%'
  from 
(


(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_0 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_1 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_2 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_3 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_4 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_5 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_6 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_7 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_8 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_9 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_10 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_11 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_12 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_13 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_14 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_15 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_16 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_17 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_18 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_19 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_20 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_21 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_22 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_23 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_24 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_25 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_26 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_27 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_28 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_29 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_30 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_31 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_32 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_33 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_34 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_35 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_36 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_37 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_38 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_39 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_40 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_41 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_42 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_43 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_44 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_45 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_46 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_47 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_48 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_49 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_50 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_51 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_52 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_53 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_54 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_55 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_56 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_57 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_58 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_59 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_60 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_61 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_62 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_63 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_64 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_65 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_66 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_67 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_68 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_69 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_70 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_71 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_72 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_73 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_74 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_75 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_76 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_77 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_78 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_79 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_80 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_81 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_82 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_83 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_84 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_85 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_86 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_87 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_88 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_89 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_90 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_91 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_92 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_93 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_94 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_95 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_96 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_97 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_98 where add_date>'2016-12-08' and type =202 group by info_id) union all
(select jid,info_id,date(max(add_date)) days,count(1) total, sum(has_read) read_count, sum(case operation when 1 then 1 else 0 end) operate_count from tb_c2c_invitation_99 where add_date>'2016-12-08' and type =202 group by info_id)


) as m group by m.info_id order by m.days desc,m.info_id desc