CREATE TABLE `sms_down_batch_170123` (
  `id` bigint(20) NOT NULL,
  `customer_id` int(11) DEFAULT '0' COMMENT '客户账号ID',
  `dest` varchar(20) DEFAULT NULL COMMENT '目标手机',
  `content` text COMMENT '短信内容',
  `ref` varchar(255) DEFAULT '' COMMENT '追踪参数',
  `ext` varchar(10) DEFAULT '' COMMENT '渠道参数',
  `operate_type` int(11) DEFAULT '0' COMMENT '运营商类型',
  `supplier_id` int(11) DEFAULT '0' COMMENT '服务商id',
  `supplier_ticket` varchar(100) DEFAULT '' COMMENT '上家返回票据',
  `supplier_message_id` varchar(100) DEFAULT '' COMMENT '上家返回消息id',
  `supplier_status` int(11) DEFAULT '0' COMMENT '服务商返回状态',
  `supplier_msg` varchar(100) DEFAULT '' COMMENT '服务商返回消息',
  `supplier_processed` int(11) DEFAULT '0' COMMENT '服务商回调是否已处理',
  `total_piece` int(11) DEFAULT '0' COMMENT '总分片',
  `total_count` int(11) DEFAULT '0' COMMENT '总条数',
  `success_count` int(11) DEFAULT '0' COMMENT '成功条数',
  `fail_count` int(11) DEFAULT '0' COMMENT '失败条数',
  `fail_mobiles` varchar(200) DEFAULT '' COMMENT '失败手机列表',
  `request_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '客户请求发送短信时间',
  `callback_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '服务商返回状态时间',
  `send_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '服务商发送短信时间',
  `send_using` int(11) DEFAULT '0' COMMENT '发送延迟时间',
  `callback_using` int(11) DEFAULT '0' COMMENT '回调延迟时间',
  `customer_status` int(11) DEFAULT '0' COMMENT '下发客户状态',
  `customer_call_times` int(11) DEFAULT '0' COMMENT '下发客户消息次数',
  `customer_next_call_time` datetime DEFAULT NULL COMMENT '下次回调时间',
  `customer_processed` int(11) DEFAULT '0' COMMENT '回调下家是否成功',
  `request_type` int(11) DEFAULT '2' COMMENT '请求状态：1正常、2测试',
  `customer_cost` int(11) DEFAULT '0' COMMENT '下家客户花费',
  `supplier_cost` int(11) DEFAULT '0' COMMENT '上家服务商花费',
  `status` int(11) DEFAULT NULL,
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间',
  `update_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据变动时间',
  PRIMARY KEY (`id`),
  KEY `idx_callback_time` (`callback_time`),
  KEY `idx_create_date` (`create_date`),
  KEY `idx_dest` (`dest`),
  KEY `idx_customer_create_date` (`customer_id`,`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='短信发送记录'